# Telegram Bot
telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_NAME}
    pin-code: ${BOT_PIN}
  
# Database
spring:
  datasource:
    url: jdbc:postgresql://${DB_PATH}/data_miner_bot
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
#
service:
  getNew: ${BASE_URL}/tender/get/new
  getDetail: ${BASE_URL}/tender/info
  getUpdate: ${BASE_URL}/tender/verify
  getDocs: ${BASE_URL}/tender/docs
#
app:
  crone:
    notification: ${CRONE_NOTIF}
    verify: ${CRONE_VERIFY}
server:
  port: 8082


