# Telegram Bot
bot:
  token: ${BOT_TOKEN}
  name: ${BOT_NAME}
  
  # Database
spring:
  datasource:
    url: jdbc:postgresql://${DB_PATH}/data_miner_bot
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml